# Changes here will be overwritten by Copier
_commit: v0.4.1
_src_path: https://github.com/linkml/linkml-project-copier
add_example: true
copyright_year: '2025'
email: cjmungall@lbl.gov
full_name: Chris Mungall
gh_action_docs_preview: false
gh_action_pypi: true
github_org: bioepic-data
license: BSD-3-Clause
project_description: Reverse engineered FAO soil database
project_name: fao-soils
project_slug: fao_soils

